# Generated by Django 4.1.7 on 2023-04-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0003_rename_username_admin_log_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='stud_image',
            field=models.ImageField(blank=True, default='Nil', upload_to='stud_image/'),
        ),
    ]
