# Generated by Django 4.1.7 on 2023-04-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0004_student_stud_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='backlog',
            field=models.IntegerField(),
        ),
    ]
