# Generated by Django 4.1.7 on 2023-04-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0005_alter_student_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default='nil', max_length=255, unique=True),
        ),
    ]
