# Generated by Django 4.1.7 on 2023-04-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0007_student_gpa_cgpa'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='student_gpa',
            constraint=models.UniqueConstraint(fields=('student', 'semester'), name='unique_student_semester'),
        ),
    ]
