# Generated by Django 4.1.7 on 2023-04-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0008_student_gpa_unique_student_semester'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student_gpa',
            name='unique_student_semester',
        ),
    ]
