# Generated by Django 4.1.7 on 2023-04-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0010_remove_student_gpa_cgpa_student_cgpa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_cgpa',
            old_name='semester',
            new_name='sem',
        ),
    ]
