# Generated by Django 4.1.7 on 2023-04-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0011_rename_semester_student_cgpa_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_gpa',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
    ]
