# Generated by Django 4.1.7 on 2023-04-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0012_student_gpa_cgpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_gpa',
            name='cgpa',
        ),
    ]
