# Generated by Django 4.1.7 on 2023-04-11 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0013_auto_20230411_1251'),
    ]

    operations = [
    ]
