# Generated by Django 4.1.7 on 2023-04-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0014_auto_20230411_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_gpa',
            name='cgpa',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
