# Generated by Django 4.1.7 on 2023-04-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0017_add_tpo_delete_student_cgpa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=100)),
                ('company_address', models.CharField(default='', max_length=100)),
                ('company_number', models.CharField(default='', max_length=10)),
                ('company_mail', models.CharField(default='', max_length=100)),
                ('contact_person_name', models.CharField(default='', max_length=12)),
                ('contact_person_number', models.CharField(default='', max_length=12)),
                ('password', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
