# Generated by Django 4.1.7 on 2023-04-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0018_add_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Job_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(default='', max_length=100)),
                ('job_detail', models.CharField(default='', max_length=100)),
                ('job_criteria', models.CharField(default='', max_length=100)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
