# Generated by Django 4.1.7 on 2023-04-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0019_add_job_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_job_post',
            name='created_date',
            field=models.DateField(),
        ),
    ]
