# Generated by Django 4.1.7 on 2023-04-26 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0020_alter_add_job_post_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job_post',
            name='company_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placement_app.add_company'),
            preserve_default=False,
        ),
    ]
