# Generated by Django 4.1.7 on 2023-04-26 05:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0021_add_job_post_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='', max_length=100)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_app.add_job_post')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placement_app.student')),
            ],
        ),
    ]
