# Generated by Django 4.1.7 on 2023-04-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0022_jobpostapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostapplication',
            name='Eligibilty',
            field=models.CharField(default='', max_length=100),
        ),
    ]
