# Generated by Django 4.1.7 on 2023-04-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0023_jobpostapplication_eligibilty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_job_post',
            name='job_detail',
        ),
        migrations.AddField(
            model_name='add_job_post',
            name='job_description',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
