# Generated by Django 4.1.7 on 2023-04-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0024_remove_add_job_post_job_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostapplication',
            name='company_ids',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='placement_app.add_company'),
            preserve_default=False,
        ),
    ]
