# Generated by Django 4.1.7 on 2023-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0026_remove_jobpostapplication_company_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_job_post',
            name='verification',
            field=models.CharField(default='Requested', max_length=100),
        ),
    ]
