# Generated by Django 4.1.7 on 2023-05-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0027_add_job_post_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_gpa',
            name='gpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
