# Generated by Django 4.1.7 on 2023-05-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement_app', '0028_alter_student_gpa_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_interview',
            name='interview_remarks',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='schedule_interview',
            name='interview_result',
            field=models.CharField(default='', max_length=100),
        ),
    ]
